obj-$(CONFIG_MACH_U8800) += board-u8800.o
obj-$(CONFIG_MACH_U8800) += board-u8800-regulator.o
obj-$(CONFIG_MACH_U8800) += board-u8800-gpiomux.o
obj-$(CONFIG_MACH_U8800) += board-u8800-regulator.o
obj-$(CONFIG_MACH_U8800) += board-u8800-rfkill.o
obj-$(CONFIG_MACH_U8800) += board-u8800-battery.o


