obj-$(CONFIG_MACH_U8860) += board-u8860.o
obj-$(CONFIG_MACH_U8860) += board-u8860-regulator.o
obj-$(CONFIG_MACH_U8860) += board-u8860-gpiomux.o
obj-$(CONFIG_MACH_U8860) += board-u8860-regulator.o
obj-$(CONFIG_MACH_U8860) += board-u8860-rfkill.o
obj-$(CONFIG_MACH_U8860) += board-u8860-battery.o

